### ISSUE TITLE
Joyn.at

### ISSUE THREAD

**Issue by Portisch** [knaerzche/plugin.video.joyn#16]
Hi,

Joyn is now available in Austria. Is there a chance this will be implemented?

joyn.de does not work in browser, joyn.at must be used.

**Comment by flashkiller999** [comment]
Hello,
I would also be interested in the ability to use this plugin with the Austrian version of joyn.
Thanks in advance

**Comment by Portisch** [comment]
it's already be done:
https://github.com/Maven85/plugin.video.joyn/tree/matrix
