### ISSUE TITLE
 Neue Videos fehlen für Voice of Germany

### ISSUE THREAD

**Issue by pejobo** [knaerzche/plugin.video.joyn#2]
Auf der Webseite ("/serien/the-voice-of-germany") werden für Staffel 9 die Episoden 16 bis 8 angezeigt, über das Plugin ist die neuste angezeigte Episode 14. Bei anderen Serien konnte ich das nicht beobachten.

**Comment by mobsean** [comment]
Konnte den Fehler reproduzieren. Auszug kodi.log: https://pastebin.com/edcksm6y

```
ERROR: C:\Users\xxx\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              elif res.tzname and res.tzname in time.tzname:
```

**Comment by pejobo** [comment]
Ich habe keine Ausgaben im Log..

**Comment by knaerzche** [comment]
Joyn hat die API gewechselt - über die alte waren nicht mehr alle Inhalte abrufbar - sollte mit dem neuen Release wieder laufen:
https://github.com/knaerzche/plugin.video.joyn/releases/download/0447863/plugin.video.joyn-1.9.6.zip
