### ISSUE TITLE
Videos only containing ads

### ISSUE THREAD

**Issue by pannal** [knaerzche/plugin.video.joyn#7]
Hey,

Since a couple of days ago watching _any_ video using your plugin results in constantly repeating advertisements for the whole duration of the video. Nothing of the requested content is being played.

Using the latest version on OSMC Kodi.

Is this known already?

Thanks!

**Comment by retrofreak83** [comment]
I experience the same issue. In the kodinerds forum (in case you speak German, which most likely is the fact if you want to use a VOD service broadcasting German programme :) ), it is being said that it is "likely that it will be impossible to be working again": https://www.kodinerds.net/index.php/Thread/66679-Pre-Release-Joyn-VOD-Live/?pageNo=37

**Comment by knaerzche** [comment]
I'm aware of that and there is nothing that can be done currently (and probably also not in the future). I discontinued developing this addon for that very reason.
There is ongoing (android only) development for this addon on https://github.com/Maven85/plugin.video.joyn/
